env:
  es6: true
  browser: true
  commonjs: true
  jest: true

plugins:
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  impliedStrict: true
  sourceType: "module"
  project: ./tsconfig.json

extends:
  - "htmlacademy/es6"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"

rules:
  no-alert: 1
  no-shadow:
    - off
  "@typescript-eslint/no-shadow":
    - error
